### ISSUE TITLE
Error when running depth metric script

### ISSUE THREAD

**Issue by rhodriguerrier** [Junyi42/monst3r#53]
Hi,

I am getting an error when using your depth metric script for sintel. It appears to be related to the GT and predictions having different sizes.

I started by running the following to produce the results:
```
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --master_port=29604 launch.py --mode=eval_pose --pretrained="checkpoints/MonST3R_PO-TA-S-W_ViTLarge_BaseDecoder_512_dpt.pth" --eval_dataset=sintel --output_dir="results/sintel_video_depth" --full_seq --no_crop
```
But when I try to run your depth metric script I get this error:
```
3192
  0%|                                                                                                 | 0/23 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/monst3r/depth_metric_sintel.py", line 72, in <module>
    get_video_results()
  File "/root/monst3r/depth_metric_sintel.py", line 59, in get_video_results
    depth_results, error_map, depth_predict, depth_gt = depth_evaluation(pr_depth, gt_depth, max_depth=70, align_with_lad2=True, use_gpu=True, post_clip_max=70)
  File "/root/monst3r/dust3r/depth_eval.py", line 191, in depth_evaluation
    predicted_depth = predicted_depth_original[mask]
IndexError: The shape of the mask [21800, 1024] at index 0 does not match the shape of the indexed tensor [65400, 1024] at index 0
```

Any help would be much appreciated.
Thanks

**Comment by Junyi42** [comment]
Thanks for pointing out the issue!! I have fixed it in https://github.com/Junyi42/monst3r/commit/a6276426e46739708ebd268c2a52c7b528064150.

Hope it helps!

Best
