### ISSUE TITLE
The checkpoint can't match 2 pictures

### ISSUE THREAD

**Issue by gyj155** [Junyi42/monst3r#8]
Thank you for sharing your work. 
I tried both gradio demo and local usage mentioned in [https://github.com/naver/dust3r/tree/main](url) with checkpoint changed to monst3r. But in both cases no match is found in chateau1 and chateau2. When I changed image pair into the same picture, namely chateau1 and chateau1, the matches are correct. When I use the dust3r checkpoint, there is no such problem.

```instantiating : AsymmetricCroCo3DStereo(pos_embed='RoPE100', patch_embed_cls='PatchEmbedDust3R', img_size=(512, 512), head_type='dpt', output_mode='pts3d', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), enc_embed_dim=1024, enc_depth=24, enc_num_heads=16, dec_embed_dim=768, dec_depth=12, dec_num_heads=12, freeze='encoder', landscape_only=False)
<All keys matched successfully>
 Loading a list of 2 images
- adding croco/assets/Chateau1.png with resolution 224x224 --> 512x384
- adding croco/assets/Chateau2.png with resolution 224x224 --> 512x384
 (Found 2 images)
 Inference with model on 2 image pairs
  0%|                                                    | 0/2 [00:00<?, ?it/s]/dust3r/dust3r/inference.py:44: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=bool(use_amp)):
/dust3r/dust3r/model.py:205: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
/dust3r/dust3r/inference.py:48: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
100%|████████████████████████████████████████████| 2/2 [00:01<00:00,  1.98it/s]
 init edge (0*,1*) score=np.float64(1.570457100868225)
 init loss = 0.017494309693574905
Global alignement - optimizing for:
['pw_poses', 'im_depthmaps', 'im_poses', 'im_focals']
100%|███████| 300/300 [00:06<00:00, 48.47it/s, lr=1.27413e-06 loss=0.000347576]
Traceback (most recent call last):
  File "/dust3r/demo2.py", line 61, in <module>
    reciprocal_in_P2, nn2_in_P1, num_matches = find_reciprocal_matches(*pts3d_list)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dust3r/dust3r/utils/geometry.py", line 358, in find_reciprocal_matches
    reciprocal_in_P1 = (nn2_in_P1[nn1_in_P2] == np.arange(len(nn1_in_P2)))
                        ~~~~~~~~~^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0```

**Comment by Junyi42** [comment]
Hi @gyj155,

Thanks for the feedback!

It seems that `croco/assets/Chateau1.png` and `croco/assets/Chateau2.png` is an image pair with varying lighting conditions and viewpoints. However, MonST3R is primarily trained on video data, where the sampled pairs have relatively minor changes in viewpoint and lighting. A potential solution (if you have sufficient computational resources and storage) would be to jointly train MonST3R with both the original DUSt3R dataset and dynamic video data to handle such cases better.

Best
