### ISSUE TITLE
Issue downloading Tartanair

### ISSUE THREAD

**Issue by jiadingfang** [Junyi42/monst3r#9]
I tried to download Tartanair with the provided script `download_tartanair.sh` . However running it results with the following error:

> 
> 36 files are going to be downloaded...
>   - tartanair/abandonedfactory/Hard/depth_left.zip
>   - tartanair/abandonedfactory/Hard/image_left.zip
>   - tartanair/abandonedfactory_night/Hard/depth_left.zip
>   - tartanair/abandonedfactory_night/Hard/image_left.zip
>   - tartanair/amusement/Hard/depth_left.zip
>   - tartanair/amusement/Hard/image_left.zip
>   - tartanair/carwelding/Hard/depth_left.zip
>   - tartanair/carwelding/Hard/image_left.zip
>   - tartanair/endofworld/Hard/depth_left.zip
>   - tartanair/endofworld/Hard/image_left.zip
>   - tartanair/gascola/Hard/depth_left.zip
>   - tartanair/gascola/Hard/image_left.zip
>   - tartanair/hospital/Hard/depth_left.zip
>   - tartanair/hospital/Hard/image_left.zip
>   - tartanair/japanesealley/Hard/depth_left.zip
>   - tartanair/japanesealley/Hard/image_left.zip
>   - tartanair/neighborhood/Hard/depth_left.zip
>   - tartanair/neighborhood/Hard/image_left.zip
>   - tartanair/ocean/Hard/depth_left.zip
>   - tartanair/ocean/Hard/image_left.zip
>   - tartanair/office/Hard/depth_left.zip
>   - tartanair/office/Hard/image_left.zip
>   - tartanair/office2/Hard/depth_left.zip
>   - tartanair/office2/Hard/image_left.zip
>   - tartanair/oldtown/Hard/depth_left.zip
>   - tartanair/oldtown/Hard/image_left.zip
>   - tartanair/seasidetown/Hard/depth_left.zip
>   - tartanair/seasidetown/Hard/image_left.zip
>   - tartanair/seasonsforest/Hard/depth_left.zip
>   - tartanair/seasonsforest/Hard/image_left.zip
>   - tartanair/seasonsforest_winter/Hard/depth_left.zip
>   - tartanair/seasonsforest_winter/Hard/image_left.zip
>   - tartanair/soulcity/Hard/depth_left.zip
>   - tartanair/soulcity/Hard/image_left.zip
>   - tartanair/westerndesert/Hard/depth_left.zip
>   - tartanair/westerndesert/Hard/image_left.zip
> Traceback (most recent call last):
>   File "/home/fjd/monst3r/data/download_tartanair.py", line 195, in <module>
>     content_list = get_all_s3_objects(s3, bucket_name)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/fjd/monst3r/data/download_tartanair.py", line 92, in get_all_s3_objects
>     response = s3.list_objects_v2(**list_kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/fjd/miniforge3/envs/monst3r/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/fjd/miniforge3/envs/monst3r/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (Unauthorized) when calling the ListObjectsV2 operation: Unauthorized

Appreciate it if you could help!

**Comment by Junyi42** [comment]
Hi @jiadingfang,

Thanks for pointing out the issue.

It looks like this is a very recent error of the TartanAir dataset: https://github.com/castacks/tartanair_tools/issues/57, which I didn't encounter earlier. Could you please try one solution posted here: https://github.com/boto/boto3/issues/3594.

Thanks.

**Comment by kami93** [comment]
> Hi @jiadingfang,
> 
> Thanks for pointing out the issue.
> 
> It looks like this is a very recent issue of the TartanAir dataset: [castacks/tartanair_tools#57](https://github.com/castacks/tartanair_tools/issues/57), which I didn't encounter earlier. Could you please try one solution posted here: [boto/boto3#3594](https://github.com/boto/boto3/issues/3594)?
> 
> Thanks.

The linked solution describes the server-side control of the access permission in the S3; seems irrelevant to the issue. Instead, the access & secret keys in the download script have expired, appearently. One should contact the authors of TartanAir dataset to update those keys in the script.

**Comment by Junyi42** [comment]
Closed as in https://github.com/castacks/tartanair_tools/issues/57#issuecomment-2430407313
